spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    password:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:/mappers/*.xml    # 指定mapper文件的位置
  type-aliases-package: com.liu.boot.bean      # 开启别名
  configuration:
    map-underscore-to-camel-case: true
